version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/web-client'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/functions'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/workers'
    schedule:
      interval: 'daily'
