name: Setup Web-Client Env
description: Set up node environment and install dependencies

inputs:
  working-dir:
    description: "NPM registry"
    default: "packages/web-client/"
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
    - run: npm install
      shell: bash
    - run: |
        touch .env
        echo "VITE_GA_TRACKING_ID=\"$GA_TRACKING_ID\"" >> .env
        echo "VITE_FIREBASE_API_KEY=\"$FIREBASE_API_KEY\"" >> .env
        echo "VITE_FIREBASE_AUTH_DOMAIN=\"$FIREBASE_AUTH_DOMAIN\"" >> .env
        echo "VITE_FIREBASE_PROJECT_ID=\"$FIREBASE_PROJECT_ID\"" >> .env
        echo "VITE_FIREBASE_STORAGE_BUCKET=\"$FIREBASE_STORAGE_BUCKET\"" >> .env
        echo "VITE_FIREBASE_MESSAGING_SENDER_ID=\"$FIREBASE_MESSAGING_SENDER_ID\"" >> .env
        echo "VITE_FIREBASE_APP_ID=\"$FIREBASE_APP_ID\"" >> .env
        echo "VITE_FIREBASE_MEASUREMENT_ID=\"$FIREBASE_MEASUREMENT_ID\"" >> .env
        echo "VITE_CLOUDFLARE_WORKERS_API_HOST=\"$CLOUDFLARE_WORKERS_API_HOST\"" >> .env
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      env:
        GA_TRACKING_ID: "G-S9P26021F9"
        FIREBASE_API_KEY: "AIzaSyAeTkffJlMN3pnzU4sBzxwo6NCl4giaOTY"
        FIREBASE_AUTH_DOMAIN: "hot-or-not-5d8ad.firebaseapp.com"
        FIREBASE_PROJECT_ID: "hot-or-not-5d8ad"
        FIREBASE_STORAGE_BUCKET: "hot-or-not-5d8ad.appspot.com"
        FIREBASE_MESSAGING_SENDER_ID: "442139438721"
        FIREBASE_APP_ID: "1:442139438721:web:b7e616f50feaa67ad12780"
        FIREBASE_MEASUREMENT_ID: "G-LDBZXMYM4E"
        CLOUDFLARE_WORKERS_API_HOST: "https://hot-or-not-upload-api-main.go-bazzinga.workers.dev"
