name: Setup Web-Client Env
description: Set up node environment and install dependencies

inputs:
  working-dir:
    description: "NPM registry"
    default: "packages/web-client/"
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Setup environment
      shell: bash
      run: |
        touch .env
        echo "VITE_GA_TRACKING_ID=\"$GA_TRACKING_ID\"" >> .env
        echo "VITE_CLOUDFLARE_WORKERS_API_HOST=\"$CLOUDFLARE_WORKERS_API_HOST\"" >> .env
        echo "VITE_WEBCLIENT_CANISTER_ID=\"$WEBCLIENT_CANISTER_ID\"" >> .env
      working-directory: ${{ inputs.working-dir }}
      env:
        GA_TRACKING_ID: "G-S9P26021F9"
        CLOUDFLARE_WORKERS_API_HOST: "https://hot-or-not-upload-api-main.go-bazzinga.workers.dev"
        WEBCLIENT_CANISTER_ID: "vyatz-hqaaa-aaaam-qauea-cai"
