# fly.toml app configuration file generated for hot-or-not-web-client on 2023-12-21T11:01:58+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hot-or-not-web-client"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
