[package]
name = "shared_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.16"
ic-cdk = "0.5.6"
ic-stable-memory = "0.2.3"
serde = "1.0.144"
speedy = "0.8.3"
