[package]
name = "individual_user_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.16"
ic-cdk = "0.5.7"
ic-cdk-macros = "0.5.7"
ic-cron = "0.7.0"
ic-stable-memory = "0.2.4"
individual_user_template_lib = { path = "../lib" }
serde = "1.0.144"
shared_utils = { path = "../../../lib/shared_utils" }
speedy = "0.8.3"
