[package]
name = "post_cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.16"
ic-cdk = "0.5.7"
ic-cdk-macros = "0.6.6"
ic-stable-memory = "0.2.4"
post_cache_lib = { path = "../lib" }
shared_utils = { path = "../../../lib/shared_utils" }
serde = "1.0.144"
speedy = "0.8.3"
