[package]
name = "user_index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-kit = "0.4.8"
candid = "0.7.16"
ic-cdk = "0.5.6"
ic-cdk-macros = "0.5.6"
ic-stable-memory = "0.2.3"
speedy = "0.8.3"
