name: Deploy all canisters to IC mainnet on push to main
on:
  push:
    branches:
      - main
    paths:
      - 'packages/ic/**'
      - '.github/workflows/all_canisters_main_deploy.yml'

jobs:
  deploy:
    name: Deploy all canisters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Add Rust wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Install DFX
        run: DFX_VERSION=0.12.1 sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
      - name: Initialize DFX identities
        run: dfx identity list
      - name: Import DFX identity
        run: |
          touch actions_identity.pem
          echo "${{ secrets.CANISTER_CONTROLLER_SECRET_KEY }}" > actions_identity.pem
          dfx identity import --disable-encryption actions actions_identity.pem
          rm actions_identity.pem
          dfx identity use actions
      - name: Cache rust dependencies, build output and DFX build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            .dfx/
          key: ${{ runner.os }}-deploy-${{ hashFiles('**/Cargo.lock') }}
      - name: Build configuration canister
        run: |
          dfx build --network ic configuration
          gzip -f -1 ./target/wasm32-unknown-unknown/release/configuration.wasm
      - name: Build data_backup canister
        run: |
          dfx build --network ic data_backup
          gzip -f -1 ./target/wasm32-unknown-unknown/release/data_backup.wasm
      - name: Build individual_user_template canister
        run: |
          dfx build --network ic individual_user_template
          gzip -f -1 ./target/wasm32-unknown-unknown/release/individual_user_template.wasm
      - name: Build user_index canister
        run: |
          dfx build --network ic user_index
          gzip -f -1 ./target/wasm32-unknown-unknown/release/user_index.wasm
      - name: Build post_cache canister
        run: |
          dfx build --network ic post_cache
          gzip -f -1 ./target/wasm32-unknown-unknown/release/post_cache.wasm
      - name: Deploy configuration canister
        run: dfx canister install configuration --network ic --mode upgrade --argument "(record { })"
      - name: Deploy data_backup canister
        run: dfx canister install data_backup --network ic --mode upgrade --argument "(record { })"
      - name: Deploy post_cache canister
        run: dfx canister install post_cache --network ic --mode upgrade --argument "(record { known_principal_ids = vec {} })"
      # - name: Backup user_index canister
      #   run: dfx canister call user_index backup_data_to_backup_canister --network ic
      - name: Deploy user_index canister
        run: dfx canister install user_index --network ic --mode upgrade --argument "(record {})"
      - name: Loop through and deploy all individual user canisters
        run: dfx canister call user_index update_user_index_upgrade_user_canisters_with_latest_wasm --network ic --async
