name: Canisters test suite run on any push except main
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'packages/ic/**'
      - '.github/workflows/all_canisters_test_suite_on_any_push.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run canister test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Add Rust wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install DFX
        run: DFX_VERSION=0.12.1 sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
      - name: Initialize DFX identities
        run: dfx identity list
      - name: Import DFX identity
        run: |
          touch actions_identity.pem
          echo "${{ secrets.CANISTER_CONTROLLER_SECRET_KEY }}" > actions_identity.pem
          dfx identity import --disable-encryption actions actions_identity.pem
          rm actions_identity.pem
          dfx identity use actions
      - name: Cache rust dependencies, build output and DFX build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            .dfx/
          key: ${{ runner.os }}-testing-${{ hashFiles('**/Cargo.lock') }}
      - name: Start local replica
        run: dfx start --background
      - name: Provision local canister IDs for the canisters
        run: |
          dfx canister create --no-wallet configuration
          dfx canister create --no-wallet individual_user_template
          dfx canister create --no-wallet user_index
          dfx canister create --no-wallet post_cache
      - name: Stop local replica
        run: dfx stop
      - name: Build configuration canister
        run: |
          dfx build configuration
          gzip -f -1 ./target/wasm32-unknown-unknown/release/configuration.wasm
      - name: Build individual_user_template canister
        run: |
          dfx build individual_user_template
          gzip -f -1 ./target/wasm32-unknown-unknown/release/individual_user_template.wasm
      - name: Build user_index canister
        run: |
          dfx build user_index
          gzip -f -1 ./target/wasm32-unknown-unknown/release/user_index.wasm
      - name: Build post_cache canister
        run: |
          dfx build post_cache
          gzip -f -1 ./target/wasm32-unknown-unknown/release/post_cache.wasm

      - name: Run canister test suite
        run: cargo test
