name: Deploy backend
on:
  push:
    branches:
      - main
    paths:
      - 'packages/backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: DFX_VERSION=0.9.3 sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
      - run: dfx identity list
      # - run: |
      #    touch actions_identity.pem
      #    echo "${{ secrets.ACTIONS_IDENTITY_SECRET }}" > actions_identity.pem
      #    dfx identity import actions actions_identity.pem
      #    rm actions_identity.pem
      #    dfx identity use actions
      # - run: dfx identity --network ic set-wallet ${{ secrets.ACTIONS_IDENTITY_DEFAULT_WALLET }}
      # - run: dfx deploy --network ic backend
