name: ex/tests
on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/experiments/**"
      - ".github/workflows/experiments-test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  svelte-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        shell: bash
        run: npm install

      - name: Running svelte-check
        run: npm run ex:check

      - name: Building static version
        run: npm run ex:build:static
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          GA_TRACKING_ID: "G-PPE5XD2VKV"

  deploy-fly-staging:
    needs: ["svelte-check"]
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm install

      - name: Deploy staging build
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.0
        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_KIT_DEPLOY_GH_ACTION }}
          FLY_ORG: gobazzinga-inc-584
        with:
          config: "ex.staging.fly.toml"
