name: Deploy functions
on:
  push:
    branches:
      - main
    paths:
      - 'packages/functions/**'
      - '.github/workflows/workers-deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  worker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
