name: Deploy Web-Client
on:
  push:
    branches:
      - main
    paths:
      - "packages/web-client/**"
      - ".github/workflows/webclient-deploy.yml"
      - ".github/workflows/webclient-setup/action.yml"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-client-deploy-dapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Set-up env
        uses: ./.github/workflows/webclient-setup
      - run: npm run wc:build:static:prod
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - run: |
          set -euxo pipefail
          DFX_VERSION=0.16.1 sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
      - run: dfx identity list
      - run: |
          touch actions_identity.pem
          echo "${{ secrets.CANISTER_CONTROLLER_SECRET_KEY }}" > actions_identity.pem
          dfx identity import --disable-encryption actions actions_identity.pem
          rm actions_identity.pem
          dfx identity use actions
      - run: dfx deploy webclient --network ic --no-wallet -y

  web-client-deploy-fly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Set-up env
        uses: ./.github/workflows/webclient-setup
      - run: npm run wc:build:prod
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy production build
        run: flyctl deploy --config ./wc.fly.toml --dockerfile ./wc.Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_KIT_DEPLOY_GH_ACTION }}
