name: Web-client changelog

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main
    paths:
      - "packages/web-client/**"
      - ".github/workflows/webclient-deploy.yml"
      - ".github/workflows/webclient-setup/action.yml"
      - ".github/workflows/webclient-test.yml"

jobs:
  google-chat-webhook:
    name: Google chat bot
    if: github.event.name == 'pull_requests'
    needs: ["deploy-preview"]
    runs-on: ubuntu-latest
    steps:
      - name: Echo details
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.actor }}
      - name: Send deployment URL to Google Chat
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: "https://chat.googleapis.com/v1/spaces/AAAA99Zbi-8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=sNxMSYeF-n104F0zcTbVaJOM5vTd88c4NffRQyskowI%3D"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"text": "PR: \"${{ github.event.pull_request.title  }}\" deployed at: \n ${{ needs.deploy-preview.outputs.previewUrl }}"}'
