name: Web-client changelog

on:
  pull_request:
    types:
      - closed
    paths:
      - "packages/web-client/**"
      - ".github/workflows/**"

jobs:
  google-chat-webhook:
    name: Google chat bot
    if: github.actor != 'dependabot[bot]' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment URL to Google Chat
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: "https://chat.googleapis.com/v1/spaces/AAAA99Zbi-8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=sNxMSYeF-n104F0zcTbVaJOM5vTd88c4NffRQyskowI%3D"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"text": "Feature: \"${{ github.event.pull_request.title  }}\" merged into main at ${{ github.event.repository.updated_at}}"}'
