name: Deploy Web-Client
on:
  push:
    branches:
      - main
    paths:
      - 'packages/web-client/**'
      - '.github/workflows/webclient-deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-client-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: |
          touch .env
          echo "VITE_GA_TRACKING_ID=\"$GA_TRACKING_ID\"" >> .env
          echo "VITE_INTERNET_IDENTITY_URL=\"$INTERNET_IDENTITY_URL\"" >> .env
          echo "VITE_FIREBASE_API_KEY=\"$FIREBASE_API_KEY\"" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=\"$FIREBASE_AUTH_DOMAIN\"" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=\"$FIREBASE_PROJECT_ID\"" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=\"$FIREBASE_STORAGE_BUCKET\"" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=\"$FIREBASE_MESSAGING_SENDER_ID\"" >> .env
          echo "VITE_FIREBASE_APP_ID=\"$FIREBASE_APP_ID\"" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=\"$FIREBASE_MEASUREMENT_ID\"" >> .env
        working-directory: packages/web-client/
        env:
          GA_TRACKING_ID: 'G-KXNH2F9QXW'
          INTERNET_IDENTITY_URL: 'https://identity.ic0.app/#authorize'
          FIREBASE_API_KEY: 'AIzaSyAeTkffJlMN3pnzU4sBzxwo6NCl4giaOTY'
          FIREBASE_AUTH_DOMAIN: 'hot-or-not-5d8ad.firebaseapp.com'
          FIREBASE_PROJECT_ID: 'hot-or-not-5d8ad'
          FIREBASE_STORAGE_BUCKET: 'hot-or-not-5d8ad.appspot.com'
          FIREBASE_MESSAGING_SENDER_ID: '442139438721'
          FIREBASE_APP_ID: '1:442139438721:web:b7e616f50feaa67ad12780'
          FIREBASE_MEASUREMENT_ID: 'G-LDBZXMYM4E'
      - run: npm run build
      - run: DFX_VERSION=0.11.1 sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
      - run: dfx identity list
      - run: |
          touch actions_identity.pem
          echo "${{ secrets.CANISTER_CONTROLLER_SECRET_KEY }}" > actions_identity.pem
          dfx identity import --disable-encryption actions actions_identity.pem 
          rm actions_identity.pem
          dfx identity use actions
      - run: dfx deploy webclient --network ic --no-wallet
