name: Deploy Web-Client
on:
  push:
    branches:
      - main
      - harsh/fix/fix-continous-frontend-reloading
    paths:
      - 'packages/web-client/**'
      - '.github/workflows/webclient-deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-client-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: |
          touch .env
          echo "VITE_INTERNET_IDENTITY_URL=\"$VITE_INTERNET_IDENTITY_URL\"" >> .env
          echo "VITE_GA_TRACKING_ID=\"$VITE_GA_TRACKING_ID\"" >> .env
        working-directory: packages/web-client/
        env:
          VITE_INTERNET_IDENTITY_URL: 'https://identity.ic0.app/#authorize'
          VITE_GA_TRACKING_ID: 'TODO'
      - run: npm run build
      - run: DFX_VERSION=0.11.1 sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
      - run: dfx identity list
      - run: |
          touch actions_identity.pem
          echo "${{ secrets.CANISTER_CONTROLLER_SECRET_KEY }}" > actions_identity.pem
          dfx identity import --disable-encryption actions actions_identity.pem 
          rm actions_identity.pem
          dfx identity use actions
      - run: dfx deploy webclient --network ic --no-wallet
