name: Deploy Cloudflare workers
on:
  push:
    paths:
      - "packages/workers/**"
      - ".github/workflows/workers-deploy.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workers-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: cd packages/workers && npm install
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_DEPLOY_API_TOKEN }}
          environment: "main"
          workingDirectory: "packages/workers/"
          secrets: |
            CLOUDFLARE_API_TOKEN
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_STREAM_IMAGES_API_TOKEN }}
