name: Deploy Cloudflare workers
on:
  push:
    branches:
      - main
    paths:
      - 'packages/workers/**'
      - '.github/workflows/workers-deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workers-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cloudflare/wrangler-action@1.3.0
        with:
        apiToken: ${{ secrets.WORKERS_API_TOKEN }}
        environment: 'main'
        workingDirectory: 'packages/workers/'
        secrets: |
          CLOUDFLARE_API_TOKEN
        env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_STREAM_API_TOKEN }}
